steps:
  - label: Build Python packages
    command:
     - make docker-clean
     - mkdir -p dist
     - .buildkite/build_whl.sh

  - wait

  - trigger: "kolibri-macos"
    label: ":mac:"
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        LE_TRIGGERED_FROM_BUILD_ID: "${BUILDKITE_BUILD_ID}"
        LE_TRIGGERED_FROM_JOB_ID: "${BUILDKITE_JOB_ID}"
        # Determines whether build will be autoblocked or not.
        # Autoblock unless there's a tag associated with the commit. Usually a release.
        LE_KOLIBRI_RELEASE: "${BUILDKITE_TAG:-false}"

    # Android build only requires whl file
  # - label: Build Android APK
  #   env:
  #     KOLIBRI_ANDROID_BUILD_MODE: dev
  #   command: &android_build
  #     - .buildkite/build_apk.sh

  - label: Build Windows installer
    command: .buildkite/build_windows_installer.sh

  - label: Build Debian Packages
    command: .buildkite/build_debian_pkgs.sh
    key: deb-build

  - trigger: "kolibri-raspbian-image"
    label: ":raspberry-pi:"
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        LE_TRIGGERED_FROM_BUILD_ID: "${BUILDKITE_BUILD_ID}"
        LE_TRIGGERED_FROM_JOB_ID: "${BUILDKITE_JOB_ID}"
        # Determines whether build will be autoblocked or not.
        # Autoblock unless there's a tag associated with the commit. Usually a release.
        LE_KOLIBRI_RELEASE: "${BUILDKITE_TAG:-false}"
    depends_on:
      - deb-build

  - wait

  - label: Upload Release Artifacts
    command: .buildkite/setup_and_upload_artifact.sh
    if: build.tag != null

  - wait

  - label: Cleaning up
    command: make docker-clean

  - wait

  - block: "Create integration testing worksheet?"
  - label: Create integration testing
    command: .buildkite/build_worksheet.sh

  # - block: "Build release APK?"
  # - label: "Build Release APK"
  #   env:
  #     KOLIBRI_ANDROID_BUILD_MODE: release
  #   command: *android_build

  - block: "Test .debs?"
  - label: Test on Trusty, Xenial, Bionic
    command:
     - mkdir -p dist
     - buildkite-agent artifact download 'dist/*.deb' dist/
     - make docker-deb-test
